server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /**
  resources:
    chain:
      strategy:
        content:
          enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: true

shiro:
  loginUrl: /login
  successUrl: /home